### ISSUE TITLE
Create Review DB Model

### ISSUE THREAD

**Issue by ltcarbonell** [UF-COP5035/Rater-System#37]
### Description
Create a new database collection for reviews with the following data model:
```
{
    teacher: Teacher object,
    student: Student object,
    class: Class object,
    review_content: Array(question:answer)
}
```
This should be created in development first, and once approved added to production.

### Affected components
- MongoDB

### Linked tickets
- [ ] Create Student DB Model #36 
- [ ] Create Class DB Model #38
- [ ] Create Teacher DB Model #39
