### ISSUE TITLE
Create Administrator DB Model

### ISSUE THREAD

**Issue by ltcarbonell** [UF-COP5035/Rater-System#40]
### Description
Create a new database collection for administrators with the following data model:
```
{
    username: String,
    classes: Array(class objects),
    reviews: Array(review objects)
    students: Array(student objects),
    teachers: Array(student objects),
}
```
This should be created in development first, and once approved added to production.

### Affected components
- MongoDB

### Linked tickets
- [ ] Create Student DB Model #36 
- [ ] Create Review DB Model #37 
- [ ] Create Classes DB Model #38 
- [ ] Create Teachers DB Model #39
